name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["windows", "ubuntu", "macos"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v1.0.1
    - name: Perform tests
      run: scala-cli test .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package
      run: scala-cli --power package --native-image . -o dist/${{ matrix.os }}-dotenv-github-release-updater --jvm-index https://raw.githubusercontent.com/coursier/jvm-index/d958ac261071f800de6341444dc8df98e9dd260c/index.json --graalvm-jvm-id graalvm-java20:20.0.1
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: dist
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist/
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.short-sha.outputs.sha }}
          target_commitish: ${{ github.sha }}
          prerelease: true
          tag_name: ${{ steps.short-sha.outputs.sha }}
          fail_on_unmatched_files: true
          files: |
            dist/**/*
          body: |
            Created from: ${{ github.sha }}
