name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v1.0.1
    - name: Perform tests
      run: scala-cli test .
    - name: Package
      run: scala-cli --power package --native-image . -o dotenv-github-release-updater --jvm-index https://raw.githubusercontent.com/coursier/jvm-index/d958ac261071f800de6341444dc8df98e9dd260c/index.json --graalvm-jvm-id graalvm-java20:20.0.1
